### ISSUE TITLE
Link to "open source projects" - Github 404

### ISSUE THREAD

**Issue by cedric25** [willmendesneto/willmendesneto.github.io#2]
Hi Will,
Simply to raise a friendly minor issue with the link pointing to your github projects: https://github.com/willmendesneto/projects with which I get the 404 Github page.
Should it point to https://github.com/willmendesneto?tab=repositories instead?
Nice and neat landing page!
Cheers,
Cedric

**Comment by willmendesneto** [comment]
Hi @cedric25.

Thanks for raise the issue. It's solved on 8d02e186780d59ffe3c2e457e62a4cb702a99260
